# Generated by Django 3.0.7 on 2020-12-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createPoll', '0003_question_pollby'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='selectedChoice',
            field=models.IntegerField(default=0),
        ),
    ]
