# Generated by Django 3.0.7 on 2020-12-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createPoll', '0005_auto_20201212_2106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voter',
        ),
    ]
