# Generated by Django 3.0.7 on 2020-12-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createPoll', '0007_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='votePercentage',
            field=models.FloatField(default=0),
        ),
    ]
