# Generated by Django 3.0.7 on 2020-12-13 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createPoll', '0008_choices_votepercentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='votePercentage',
        ),
    ]
