# Generated by Django 3.0.7 on 2020-12-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateJoined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
