# Generated by Django 3.0.7 on 2020-12-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201208_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateJoined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
